import type { NextPage } from 'next'
import Head from 'next/head'
import 'mapbox-gl/dist/mapbox-gl.css';


const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl.css"
          rel="stylesheet"
        />
      </Head>

      <h1>Hey</h1>
      
    </div>
  )
}

export default Home
